# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    name: Build and Compile Executables
    strategy:
      fail-fast: false  # needed to keep running other OS builds even if one fails
      matrix:
        os:
          - ubuntu-20.04
          #- windows-latest
        architecture:
          #- amd64
          #- armv8l
          - i386

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Cross-Compilation Tools
        if: matrix.architecture == 'armv8l'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

      - name: Set up i386 Compilation Tools
        if: matrix.architecture == 'i386'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib musl-tools

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools build requests flask PyYAML Pillow olefile

      - name: Build Source Distribution
        run: python setup.py sdist

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: ycast/launch.py
          mode: onefile
          include-data-files: |
            ycast/templates/index.html=ycast/templates/index.html
            ycast/static/script.js=ycast/static/script.js
            ycast/static/style.css=ycast/static/style.css
          output-dir: build
          output-file: ycast

      - name: Upload Compilation Report
        if: always()  # run even if the compile failed
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }} compilation report
          path: compilation-report.xml

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/ycast

      - name: Test Executable on Windows
        if: runner.os == 'Windows'
        run: ./build/*.exe --version

      - name: Test Executable on Linux
        if: runner.os != 'Windows'
        run: ./build/ycast --help
